[PLUGIN-1017] Escape column names
data-integrations/database-plugins pull request #514
Opened 2024-10-07 07:37 UTC by psainics

## Escape column names

Jira : [PLUGIN-1017](https://cdap.atlassian.net/browse/PLUGIN-1017)

### Description

If column name is a MySQL reserved keyword say `insert` the query will fail due to incorrect sql syntax.
This PR fixes this issue by escaping the column names using back ticks.

Similar column escapes is used in other plugins. Ref [CloudSQLPostgreSQLSink](https://github.com/data-integrations/database-plugins/blob/a83eaac204fdff5f9a81fbacc938114d040dd844/cloudsql-postgresql-plugin/src/main/java/io/cdap/plugin/cloudsql/postgres/CloudSQLPostgreSQLSink.java#L107-L118) 

### Code change

- Modified `CloudSQLMySQLSink.java`

### Unit Tests

- Added `CloudSQLMySQLSinkTest.java`

![image](https://github.com/user-attachments/assets/9b8fe4bc-e7a4-4dae-be2f-0f58ea4b664e)

2024-10-17 12:35 UTC, ritwiksahani approved these changes

2024-10-22 06:04 UTC, itsankit-google requested changes
I know this will fix one part of the problem but now this turns into a backward incompatible change because let's say if MySQL by default convert all identifiers to lowercase and if a cx has a pipeline which has any column name in uppercase, it will start failing.

The right thing to do would be as described in JIRA to introduce a new config named `Field Mapping` which can make any CDAP field in the schema to a different name and will be passed as quoted.

2024-10-22 06:20 UTC, psainics commented
> I know this will fix one part of the problem but now this turns into a backward incompatible change because let's say if MySQL by default convert all identifiers to lowercase and if a cx has an existing pipeline which has any column name in uppercase, it will start failing.
> 
> The right thing to do would be as described in JIRA to introduce a new config named `Field Mapping` which can map any CDAP field in the schema to a different name and will be passed as quoted.

Mysql Col names are not case sensitivity.

2024-10-22 09:33 UTC, itsankit-google requested changes
Please do the same changes for `MySQL` sink as well.

2024-10-22 09:34 UTC, itsankit-google commented
> > I know this will fix one part of the problem but now this turns into a backward incompatible change because let's say if MySQL by default convert all identifiers to lowercase and if a cx has an existing pipeline which has any column name in uppercase, it will start failing.
> > The right thing to do would be as described in JIRA to introduce a new config named `Field Mapping` which can map any CDAP field in the schema to a different name and will be passed as quoted.
> 
> Mysql Col names are not case sensitivity.

Discussed offline, to address the larger problem in future.

2024-10-28 16:04 UTC, itsankit-google commented on mysql-plugin/src/main/java/io/cdap/plugin/mysql/MysqlDBRecord.java
> +  }
why this change?

2024-10-28 16:07 UTC, psainics commented on mysql-plugin/src/main/java/io/cdap/plugin/mysql/MysqlDBRecord.java
> +  }
Ref: https://github.com/data-integrations/database-plugins/blob/acd47fa18a8bcfbc382c0c9ba92e7395e0e17f8b/oracle-plugin/src/main/java/io/cdap/plugin/oracle/OracleSinkDBRecord.java#L44-L52


This is done to get the cols values from schema with ignoring case.

If cols in CDAP schema are in different case from the cols in the mysql DB, ignoring case is required else we will get null values.

2024-10-30 05:44 UTC, itsankit-google approved these changes

2024-11-05 03:59 UTC, merged